# description
name: "Leszek Pietrzak tata programista"
description: "Leszek Pietrzak tata programista strona firmowa"
keywords: ""
author: "Leszek Pietrzak"
email: "tataprogramista@proton.me"
language: "pl-PL"

# address settings
baseurl: "http://tataprogramista.biz"

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
  auto_ids: false
timezone: Europe/Warsaw
# 0 to 65535
port: 2038

exclude:
  - node_modules
  - LICENSE
  - README.md
  - package.json
  - package-lock.json
